name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  test-backend:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Clean with Gradle Wrapper
        run: ./gradlew clean

      - name: Unit Test with Gradle Wrapper
        run: ./gradlew test --tests "com.example.*"